name: Run mypy and python-only unit and integration tests

on:
  push:
  workflow_dispatch:

env:
  PROXY_URL: https://efile-test.suffolklitlab.org
  PROXY_API_KEY: ${{ secrets.EFILE_PROXY_API_KEY }}
  TYLER_USER_EMAIL: ${{ secrets.TYLER_EMAIL }}
  TYLER_USER_PASSWORD: ${{ secrets.TYLER_PASSWORD }}

# Allow only one concurrent test-run, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as stopping integration tests mid-run could end up in a bad state
concurrency:
  group: "tests"
  cancel-in-progress: false

jobs:
  test-efspintegration:
    runs-on: ubuntu-latest
    name: Run python-only unit and integration tests
    steps:
      - run: sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev build-essential python3-dev libldap2-dev libsasl2-dev slapd ldap-utils tox lcov libzbar0 libaugeas0 augeas-lenses
      - run: echo "ISUNITTEST=true" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run mypy
        run: uv run python -m mypy . --exclude '^build/' --explicit-package-bases

      - name: Run tests
        run: |
          if [[ -f docassemble/__init__.py ]]; then
            mv docassemble/__init__.py docassemble/__init__.py.bak
          fi
          uv run python -m unittest discover docassemble