name: Run python only unit tests and mypy

on:
  push:
  workflow_dispatch:

jobs:
  test-efspintegration:
    runs-on: ubuntu-latest
    name: Run python only unit tests
    steps:
      - run: sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev build-essential python3-dev libldap2-dev libsasl2-dev slapd ldap-utils tox lcov valgrind libzbar0
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install --editable .
      - run: pip install -r docassemble/*/requirements.txt
      - run: python -m mypy .
      - run: python -m unittest discover
