name: Run python only unit tests and mypy

on:
  push:
  workflow_dispatch:

jobs:
  test-efspintegration:
    runs-on: ubuntu-latest
    name: Run python only unit tests
    steps:
      - uses: SuffolkLITLab/ALActions/pythontests@main
